mushkin_vitforms_homepage:
    path:     /
    defaults: { _controller: MushkinVitformsBundle:Default:index }

AddUser:
    path:     /AddUser
    defaults: { _controller: MushkinVitformsBundle:Default:AddUser }
